CREATE TABLE "company_details" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"team_members_count" integer DEFAULT 0,
	"years_experience" integer DEFAULT 0,
	"projects_completed" integer DEFAULT 0,
	"company_name" varchar(200) NOT NULL,
	"tagline" varchar(300),
	"about_us" text,
	"vision" text,
	"mission" text,
	"office_address" text,
	"office_address_url" varchar(500),
	"office_phone" varchar(50),
	"contact_email" varchar(255),
	"support_email" varchar(255),
	"operational_hours" text,
	"timezone" varchar(50) DEFAULT 'Asia/Jakarta',
	"website_url" varchar(300),
	"linkedin_url" varchar(300),
	"instagram_url" varchar(300),
	"facebook_url" varchar(300),
	"twitter_url" varchar(300),
	"youtube_url" varchar(300),
	"founded_year" integer,
	"company_size" varchar(50),
	"industry_focus" jsonb,
	"certifications" jsonb,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
